### ISSUE TITLE
SCP-079 bugs and missing cells/doors

### ISSUE THREAD

**Issue by Polaris1777** [Deep-Gaming-SCP-RP/Deep-Gaming-Issues#11]
I believe Josh is already aware for most of this, but I'll write it here for documentation purposes:

*SCP-079 does not have access to the following SCPs:

966
372
457
076-2

*SCP-079 can not type in OOC chat when RDC is OFF. 

*(Unconfirmed) SCP-079 cannot breach 682 due to the fence in his cell, as 079 only has access to the blast door.

*SCP-079 does not have access to the HCZ Stairs door (Intentional?)

*SCP-079 has no access to Entrance Zone (Cannot do anything in E.Z, including assisting escaping D-Class by opening the gate doors or RDC room doors)

*SCP-079 can be force AFKed (obviously, he can't move)

**Comment by JoshJOkayguy** [comment]
> *SCP-079 can not type in OOC chat when RDC is OFF.

Fixed
> *(Unconfirmed) SCP-079 cannot breach 682 due to the fence in his cell, as 079 only has access to the blast door.

Will be fixed tomorrow (after the update is applied)
> *SCP-079 has no access to Entrance Zone (Cannot do anything in E.Z, including assisting escaping D-Class by opening the gate doors or RDC room doors)

We didn't have time when we first configured it, this will be changed soon
> *SCP-079 can be force AFKed (obviously, he can't move)

No more AFK system
