### ISSUE TITLE
280 Lua Error upon DC

### ISSUE THREAD

**Issue by ynot01** [Deep-Gaming-SCP-RP/Deep-Gaming-Issues#13]
280 DCed and this error happened
[deep280] addons/deep280/lua/weapons/scp280/shared.lua:133: Tried to use a NULL entity!
  1. SetRenderMode - [C]:-1
   2. unknown - addons/deep280/lua/weapons/scp280/shared.lua:133

**Comment by JoshJOkayguy** [comment]
I'll have this fixed soon.
