### ISSUE TITLE
1.4 Bugs catalogue (UA Attention Required)

### ISSUE THREAD

**Issue by Polaris1777** [Deep-Gaming-SCP-RP/Deep-Gaming-Issues#20]
Foundation AI does not spawn with Noclip

**Comment by JoshJOkayguy** [comment]
All spawn locations as far as I'm aware have now been fixed

**Comment by kkenney-bit** [comment]
All map issues currently known have been resolved for the upcoming patch.

**Comment by JoshJOkayguy** [comment]
Confirm if fixed

**Comment by kkenney-bit** [comment]
Confirmed

**Comment by JoshJOkayguy** [comment]
FO AI swep being made
