### ISSUE TITLE
079 cam issues

### ISSUE THREAD

**Issue by ynot01** [Deep-Gaming-SCP-RP/Deep-Gaming-Issues#23]
~~cant open 096's top door (it only has button on one side, maybe map issue?)~~
no 610 cam
~~Gate A door button does nothing!!~~
no Gate B door button
~~682 hoist button doesn't work~~
~~106 electromagnet button doesn't work~~
~~D Block gate button doesn't work~~
~~Temporary cells button (at stationary cells cam) doesn't work~~

~~079 cannot use /scp unless RDC is on~~

**Comment by JoshJOkayguy** [comment]
Looking into it. Seems like some of these are map issues (I can remedy them on my end).

**Comment by JoshJOkayguy** [comment]
Anything I edited your issue to cross out is not fixed in game, they were just caused by bugs with the script itself and have been fixed. I will need to go back and reconfigure these soon.

**Comment by JoshJOkayguy** [comment]
Should be good, will reopen if more issues arise
