### ISSUE TITLE
Textscreens in D block and Sec Bunks

### ISSUE THREAD

**Issue by ManManson2** [Deep-Gaming-SCP-RP/Deep-Gaming-Issues#24]
Rule text screens in dblock aren't there (The new player text screens, the whats KOS/Detain/Okay text screens nor the line text screen)
The training textscreens/upper level prop in the trainer room haven't been replaced either. 

All of this has been missing for like a week now. Could this stuff please get replaced? Especially the training text screens and the upper level prop.

**Comment by JoshJOkayguy** [comment]
This task is up to the division leaders and COs, not staff or the development team.
