### ISSUE TITLE
Foundation Armory

### ISSUE THREAD

**Issue by ManManson2** [Deep-Gaming-SCP-RP/Deep-Gaming-Issues#25]
This has been missing for like a week now with not much explanation given as to why its been missing. It was just a bunch of props and already preset npcs. Could this be replaced?

**Comment by ManManson2** [comment]
This was fixed. Only problem is the button to get out is busted. Maybe the NPCs can be moved to another location temporarily?

**Comment by JoshJOkayguy** [comment]
Sent to Kam

**Comment by JoshJOkayguy** [comment]
Fixed for next map patch
