### ISSUE TITLE
SCP Radio Issue

### ISSUE THREAD

**Issue by ManManson2** [Deep-Gaming-SCP-RP/Deep-Gaming-Issues#26]
Please for the love of redacted, make it remove your radio when you are transformed into an SCP. Some SCPS have sweps that change people into SCPS but they DO NOT REMOVE THE RADIO. So if you happened to have your radio microphone unmuted and get transformed, it causes an endless voice spam on the frequency that the offender can do NOTHING about. 

Please make it so that right before it transforms you, it STRIPS all your weapons if that is at all possible.

**Comment by JoshJOkayguy** [comment]
Fixed
