### ISSUE TITLE
Whitelists broken for quite a few IA Jobs

### ISSUE THREAD

**Issue by Unionnn** [Deep-Gaming-SCP-RP/Deep-Gaming-Issues#28]
Deputy Constable and Corporal are the ones that I know are scuffed rn

**Comment by SEGA90Dreamcast** [comment]
Yea

**Comment by SEGA90Dreamcast** [comment]
Now that I think about it marshal and deputy constable can only be given by UA

**Comment by JoshJOkayguy** [comment]
Sent to JRB
