### ISSUE TITLE
D Class Commander Swep Issues

### ISSUE THREAD

**Issue by ManManson2** [Deep-Gaming-SCP-RP/Deep-Gaming-Issues#3]
For some reason there are a few classes that don't seem to get stuff from the D class commander. Im unsure if this is intentional but.

- Big Rich and Safe Class don't get G36C or G3A3 from Swep
- No D class get the 10k bonus from the "Give all D class 10000$" option. I thought it was just big rich and safe but apparently no d class get the benefit.

**Comment by JoshJOkayguy** [comment]
Sent to JRB

**Comment by JoshJOkayguy** [comment]
This should be fixed.
