### ISSUE TITLE
Radio Voice issue

### ISSUE THREAD

**Issue by ManManson2** [Deep-Gaming-SCP-RP/Deep-Gaming-Issues#32]
When your microphone is not muted on the radio, if a person near you voice chats, they will trigger the radio effect when they stop talking even if they aren't actually in the radio. It sometimes even shows up on the corner as if they were on radio when they really aren't. This has occured several times now since I've been on the server. Its a bit annoying and it also results in a lot of confusion at times.

**Comment by JoshJOkayguy** [comment]
Might be fixed in the future, however this addon is not ours and as far as I'm aware we do not have permission to edit it.
