### ISSUE TITLE
Disguise Kit Timer does not reset/stop after you redisguise.

### ISSUE THREAD

**Issue by talismin2** [Deep-Gaming-SCP-RP/Deep-Gaming-Issues#34]
Each time you disguise you start a timer. When the timer ends you undisguise. If you disguise after you are already disguised, it does not stop the original timer and just starts another timer. Causing you to undisguise multiple times afterwards. Just make it so each time you disguise the timer gets reset and it should fix it.

**Comment by JoshJOkayguy** [comment]
Working on it
