### ISSUE TITLE
IA Needs proper Keycards and taking keycards

### ISSUE THREAD

**Issue by MrCloudDude** [Deep-Gaming-SCP-RP/Deep-Gaming-Issues#36]
•Constable needs Level 2 Keycards (They have Level 1 Right now)

•Sergeant Needs Level 3 Keycards (Currently has level 3)

•When a D-Class buys a Fake Keycard we can't see it as a illegal weapon and we can't take it from them via right click.

**Comment by JoshJOkayguy** [comment]
Fake keycard issue is going to be a wontfix
