### ISSUE TITLE
E.C.R.F. [Custom Class] Radio Set To 0.0 Frequency On Spawn.

### ISSUE THREAD

**Issue by CalifornianKing3** [Deep-Gaming-SCP-RP/Deep-Gaming-Issues#39]
The E.C.R.F. [Custom Class] is set to have the radio frequency at 0.0 when first spawned in, this is a persisting problem (Game restarts and etc doesn't fix this). Also, radio doesn't work even when adjusted to 200.0 or other usable foundation frequencies, just makes static noises. Unsure if the other custom classes now share this problem as well. E.C.R.F. [Custom Class] needs it's spawn radio frequency to be changed to 200.0 (Gensec Comms).

**Comment by JoshJOkayguy** [comment]
Fixed
