### ISSUE TITLE
Buttons no worky on map

### ISSUE THREAD

**Issue by AshleyyRodriguez** [Deep-Gaming-SCP-RP/Deep-Gaming-Issues#4]
These buttons don't work / don't exist
![buttonnoworkey](https://user-images.githubusercontent.com/74266156/139300478-25e9b0a6-bf69-453f-b35f-21f46f827c1a.PNG)
![unknown-4](https://user-images.githubusercontent.com/74266156/139300503-9d1db04d-471b-49f2-9ab5-baadb8357b23.png)

**Comment by JoshJOkayguy** [comment]
Notified Joe

**Comment by JoshJOkayguy** [comment]
I've been told to relay that the second issue is on purpose and the first one has been fixed and will be applied in the next hotfix.
