### ISSUE TITLE
939 issues

### ISSUE THREAD

**Issue by Lenny-the-burger** [Deep-Gaming-SCP-RP/Deep-Gaming-Issues#51]
1. 939 bite has infinite range
2. 939 cant break down most doors like its meant to
3. what makes noise is really weirdly defined sometimes people can spring away from you and you wont see them, maybe just have it so if a person is moving above a certain velocity 939 can see them?
4. People can shoot you and you often still wont see them, I'm pretty sure guns are louder than footsteps
5. Sometimes people's guns are still visible even if the person themselves isn't

**Comment by Lenny-the-burger** [comment]
6. 939 sounds are missing

**Comment by JoshJOkayguy** [comment]
New 939 addon
