### ISSUE TITLE
New escape menu destroys screen

### ISSUE THREAD

**Issue by ChaoticHelix** [Deep-Gaming-SCP-RP/Deep-Gaming-Issues#67]
Im running a dual monitor, usually use discord  on the the right. tabs me out of gmod when i click it, anytime i am in escape menu and click the other screen when it tabs me out. When i reopen gmod it blackscreens my game.

**Comment by JoshJOkayguy** [comment]
Can you confirm that this is still an issue

**Comment by ChaoticHelix** [comment]
I will later tonight

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
