### ISSUE TITLE
Far Ranged Knifes Bug

### ISSUE THREAD

**Issue by ManManson2** [Deep-Gaming-SCP-RP/Deep-Gaming-Issues#7]
I'm not sure if this actually does damage but if you put a fence down you can actually see the knife strike hit far away behind it. I don't know if you can actually damage someone like this and it would be blatantly obvious but I could see situations in D block or other fenced checkpoints where this could potentially result in some nonsense kills if it does do damage. 

Video: https://gyazo.com/e972260a4df8913b2653c89e837f3134

**Comment by JoshJOkayguy** [comment]
Determine if this bug actually affects gameplay or not and get back to me.

**Comment by JoshJOkayguy** [comment]
Turns out the knives do no damage, however they do take 1 armor point each hit.
